TESTS=(
    "tests/long_string.txt"
    "-n tests/long_string.txt"
    "-b tests/long_string.txt"
    "-s tests/long_string.txt"
    "-t tests/long_string.txt"
    "-e tests/long_string.txt"
    "-n -b tests/long_string.txt"
    "-n -s tests/long_string.txt"
    "-n -t tests/long_string.txt"
    "-n -e tests/long_string.txt"
    "-b -s tests/long_string.txt"
    "-b -t tests/long_string.txt"
    "-b -e tests/long_string.txt"
    "-s -t tests/long_string.txt"
    "-s -e tests/long_string.txt"
    "-t -e tests/long_string.txt"
    "-n -b -s tests/long_string.txt"
    "-n -b -t tests/long_string.txt"
    "-n -b -e tests/long_string.txt"
    "-n -s -t tests/long_string.txt"
    "-n -s -e tests/long_string.txt"
    "-n -t -e tests/long_string.txt"
    "-b -s -t tests/long_string.txt"
    "-b -s -e tests/long_string.txt"
    "-b -t -e tests/long_string.txt"
    "-s -t -e tests/long_string.txt"
    "-n -b -s -t tests/long_string.txt"
    "-n -b -s -e tests/long_string.txt"
    "-n -b -t -e tests/long_string.txt"
    "-n -s -t -e tests/long_string.txt"
    "-b -s -t -e tests/long_string.txt"
    "-n -b -s -t -e tests/long_string.txt"
    "tests/bytes.txt"
    "-n tests/bytes.txt"
    "-b tests/bytes.txt"
    "-s tests/bytes.txt"
    "-t tests/bytes.txt"
    "-e tests/bytes.txt"
    "-n -b tests/bytes.txt"
    "-n -s tests/bytes.txt"
    "-n -t tests/bytes.txt"
    "-n -e tests/bytes.txt"
    "-b -s tests/bytes.txt"
    "-b -t tests/bytes.txt"
    "-b -e tests/bytes.txt"
    "-s -t tests/bytes.txt"
    "-s -e tests/bytes.txt"
    "-t -e tests/bytes.txt"
    "-n -b -s tests/bytes.txt"
    "-n -b -t tests/bytes.txt"
    "-n -b -e tests/bytes.txt"
    "-n -s -t tests/bytes.txt"
    "-n -s -e tests/bytes.txt"
    "-n -t -e tests/bytes.txt"
    "-b -s -t tests/bytes.txt"
    "-b -s -e tests/bytes.txt"
    "-b -t -e tests/bytes.txt"
    "-s -t -e tests/bytes.txt"
    "-n -b -s -t tests/bytes.txt"
    "-n -b -s -e tests/bytes.txt"
    "-n -b -t -e tests/bytes.txt"
    "-n -s -t -e tests/bytes.txt"
    "-b -s -t -e tests/bytes.txt"
    "-n -b -s -t -e tests/bytes.txt"
    "tests/1.txt"
    "-n tests/1.txt"
    "-b tests/1.txt"
    "-s tests/1.txt"
    "-t tests/1.txt"
    "-e tests/1.txt"
    "-n -b tests/1.txt"
    "-n -s tests/1.txt"
    "-n -t tests/1.txt"
    "-n -e tests/1.txt"
    "-b -s tests/1.txt"
    "-b -t tests/1.txt"
    "-b -e tests/1.txt"
    "-s -t tests/1.txt"
    "-s -e tests/1.txt"
    "-t -e tests/1.txt"
    "-n -b -s tests/1.txt"
    "-n -b -t tests/1.txt"
    "-n -b -e tests/1.txt"
    "-n -s -t tests/1.txt"
    "-n -s -e tests/1.txt"
    "-n -t -e tests/1.txt"
    "-b -s -t tests/1.txt"
    "-b -s -e tests/1.txt"
    "-b -t -e tests/1.txt"
    "-s -t -e tests/1.txt"
    "-n -b -s -t tests/1.txt"
    "-n -b -s -e tests/1.txt"
    "-n -b -t -e tests/1.txt"
    "-n -s -t -e tests/1.txt"
    "-b -s -t -e tests/1.txt"
    "-n -b -s -t -e tests/1.txt"
    "tests/2.txt"
    "-n tests/2.txt"
    "-b tests/2.txt"
    "-s tests/2.txt"
    "-t tests/2.txt"
    "-e tests/2.txt"
    "-n -b tests/2.txt"
    "-n -s tests/2.txt"
    "-n -t tests/2.txt"
    "-n -e tests/2.txt"
    "-b -s tests/2.txt"
    "-b -t tests/2.txt"
    "-b -e tests/2.txt"
    "-s -t tests/2.txt"
    "-s -e tests/2.txt"
    "-t -e tests/2.txt"
    "-n -b -s tests/2.txt"
    "-n -b -t tests/2.txt"
    "-n -b -e tests/2.txt"
    "-n -s -t tests/2.txt"
    "-n -s -e tests/2.txt"
    "-n -t -e tests/2.txt"
    "-b -s -t tests/2.txt"
    "-b -s -e tests/2.txt"
    "-b -t -e tests/2.txt"
    "-s -t -e tests/2.txt"
    "-n -b -s -t tests/2.txt"
    "-n -b -s -e tests/2.txt"
    "-n -b -t -e tests/2.txt"
    "-n -s -t -e tests/2.txt"
    "-b -s -t -e tests/2.txt"
    "-n -b -s -t -e tests/2.txt"
    "tests/test1.txt"
    "-n tests/test1.txt"
    "-b tests/test1.txt"
    "-s tests/test1.txt"
    "-t tests/test1.txt"
    "-e tests/test1.txt"
    "-n -b tests/test1.txt"
    "-n -s tests/test1.txt"
    "-n -t tests/test1.txt"
    "-n -e tests/test1.txt"
    "-b -s tests/test1.txt"
    "-b -t tests/test1.txt"
    "-b -e tests/test1.txt"
    "-s -t tests/test1.txt"
    "-s -e tests/test1.txt"
    "-t -e tests/test1.txt"
    "-n -b -s tests/test1.txt"
    "-n -b -t tests/test1.txt"
    "-n -b -e tests/test1.txt"
    "-n -s -t tests/test1.txt"
    "-n -s -e tests/test1.txt"
    "-n -t -e tests/test1.txt"
    "-b -s -t tests/test1.txt"
    "-b -s -e tests/test1.txt"
    "-b -t -e tests/test1.txt"
    "-s -t -e tests/test1.txt"
    "-n -b -s -t tests/test1.txt"
    "-n -b -s -e tests/test1.txt"
    "-n -b -t -e tests/test1.txt"
    "-n -s -t -e tests/test1.txt"
    "-b -s -t -e tests/test1.txt"
    "-n -b -s -t -e tests/test1.txt"
    "tests/test2.txt"
    "-n tests/test2.txt"
    "-b tests/test2.txt"
    "-s tests/test2.txt"
    "-t tests/test2.txt"
    "-e tests/test2.txt"
    "-n -b tests/test2.txt"
    "-n -s tests/test2.txt"
    "-n -t tests/test2.txt"
    "-n -e tests/test2.txt"
    "-b -s tests/test2.txt"
    "-b -t tests/test2.txt"
    "-b -e tests/test2.txt"
    "-s -t tests/test2.txt"
    "-s -e tests/test2.txt"
    "-t -e tests/test2.txt"
    "-n -b -s tests/test2.txt"
    "-n -b -t tests/test2.txt"
    "-n -b -e tests/test2.txt"
    "-n -s -t tests/test2.txt"
    "-n -s -e tests/test2.txt"
    "-n -t -e tests/test2.txt"
    "-b -s -t tests/test2.txt"
    "-b -s -e tests/test2.txt"
    "-b -t -e tests/test2.txt"
    "-s -t -e tests/test2.txt"
    "-n -b -s -t tests/test2.txt"
    "-n -b -s -e tests/test2.txt"
    "-n -b -t -e tests/test2.txt"
    "-n -s -t -e tests/test2.txt"
    "-b -s -t -e tests/test2.txt"
    "-n -b -s -t -e tests/test2.txt"
    "tests/test3.txt"
    "-n tests/test3.txt"
    "-b tests/test3.txt"
    "-s tests/test3.txt"
    "-t tests/test3.txt"
    "-e tests/test3.txt"
    "-n -b tests/test3.txt"
    "-n -s tests/test3.txt"
    "-n -t tests/test3.txt"
    "-n -e tests/test3.txt"
    "-b -s tests/test3.txt"
    "-b -t tests/test3.txt"
    "-b -e tests/test3.txt"
    "-s -t tests/test3.txt"
    "-s -e tests/test3.txt"
    "-t -e tests/test3.txt"
    "-n -b -s tests/test3.txt"
    "-n -b -t tests/test3.txt"
    "-n -b -e tests/test3.txt"
    "-n -s -t tests/test3.txt"
    "-n -s -e tests/test3.txt"
    "-n -t -e tests/test3.txt"
    "-b -s -t tests/test3.txt"
    "-b -s -e tests/test3.txt"
    "-b -t -e tests/test3.txt"
    "-s -t -e tests/test3.txt"
    "-n -b -s -t tests/test3.txt"
    "-n -b -s -e tests/test3.txt"
    "-n -b -t -e tests/test3.txt"
    "-n -s -t -e tests/test3.txt"
    "-b -s -t -e tests/test3.txt"
    "-n -b -s -t -e tests/test3.txt"
    "tests/test4.txt"
    "-n tests/test4.txt"
    "-b tests/test4.txt"
    "-s tests/test4.txt"
    "-t tests/test4.txt"
    "-e tests/test4.txt"
    "-n -b tests/test4.txt"
    "-n -s tests/test4.txt"
    "-n -t tests/test4.txt"
    "-n -e tests/test4.txt"
    "-b -s tests/test4.txt"
    "-b -t tests/test4.txt"
    "-b -e tests/test4.txt"
    "-s -t tests/test4.txt"
    "-s -e tests/test4.txt"
    "-t -e tests/test4.txt"
    "-n -b -s tests/test4.txt"
    "-n -b -t tests/test4.txt"
    "-n -b -e tests/test4.txt"
    "-n -s -t tests/test4.txt"
    "-n -s -e tests/test4.txt"
    "-n -t -e tests/test4.txt"
    "-b -s -t tests/test4.txt"
    "-b -s -e tests/test4.txt"
    "-b -t -e tests/test4.txt"
    "-s -t -e tests/test4.txt"
    "-n -b -s -t tests/test4.txt"
    "-n -b -s -e tests/test4.txt"
    "-n -b -t -e tests/test4.txt"
    "-n -s -t -e tests/test4.txt"
    "-b -s -t -e tests/test4.txt"
    "-n -b -s -t -e tests/test4.txt"
    "tests/test_1_cat.txt"
    "-n tests/test_1_cat.txt"
    "-b tests/test_1_cat.txt"
    "-s tests/test_1_cat.txt"
    "-t tests/test_1_cat.txt"
    "-e tests/test_1_cat.txt"
    "-n -b tests/test_1_cat.txt"
    "-n -s tests/test_1_cat.txt"
    "-n -t tests/test_1_cat.txt"
    "-n -e tests/test_1_cat.txt"
    "-b -s tests/test_1_cat.txt"
    "-b -t tests/test_1_cat.txt"
    "-b -e tests/test_1_cat.txt"
    "-s -t tests/test_1_cat.txt"
    "-s -e tests/test_1_cat.txt"
    "-t -e tests/test_1_cat.txt"
    "-n -b -s tests/test_1_cat.txt"
    "-n -b -t tests/test_1_cat.txt"
    "-n -b -e tests/test_1_cat.txt"
    "-n -s -t tests/test_1_cat.txt"
    "-n -s -e tests/test_1_cat.txt"
    "-n -t -e tests/test_1_cat.txt"
    "-b -s -t tests/test_1_cat.txt"
    "-b -s -e tests/test_1_cat.txt"
    "-b -t -e tests/test_1_cat.txt"
    "-s -t -e tests/test_1_cat.txt"
    "-n -b -s -t tests/test_1_cat.txt"
    "-n -b -s -e tests/test_1_cat.txt"
    "-n -b -t -e tests/test_1_cat.txt"
    "-n -s -t -e tests/test_1_cat.txt"
    "-b -s -t -e tests/test_1_cat.txt"
    "-n -b -s -t -e tests/test_1_cat.txt"
    "tests/test_2_cat.txt"
    "-n tests/test_2_cat.txt"
    "-b tests/test_2_cat.txt"
    "-s tests/test_2_cat.txt"
    "-t tests/test_2_cat.txt"
    "-e tests/test_2_cat.txt"
    "-n -b tests/test_2_cat.txt"
    "-n -s tests/test_2_cat.txt"
    "-n -t tests/test_2_cat.txt"
    "-n -e tests/test_2_cat.txt"
    "-b -s tests/test_2_cat.txt"
    "-b -t tests/test_2_cat.txt"
    "-b -e tests/test_2_cat.txt"
    "-s -t tests/test_2_cat.txt"
    "-s -e tests/test_2_cat.txt"
    "-t -e tests/test_2_cat.txt"
    "-n -b -s tests/test_2_cat.txt"
    "-n -b -t tests/test_2_cat.txt"
    "-n -b -e tests/test_2_cat.txt"
    "-n -s -t tests/test_2_cat.txt"
    "-n -s -e tests/test_2_cat.txt"
    "-n -t -e tests/test_2_cat.txt"
    "-b -s -t tests/test_2_cat.txt"
    "-b -s -e tests/test_2_cat.txt"
    "-b -t -e tests/test_2_cat.txt"
    "-s -t -e tests/test_2_cat.txt"
    "-n -b -s -t tests/test_2_cat.txt"
    "-n -b -s -e tests/test_2_cat.txt"
    "-n -b -t -e tests/test_2_cat.txt"
    "-n -s -t -e tests/test_2_cat.txt"
    "-b -s -t -e tests/test_2_cat.txt"
    "-n -b -s -t -e tests/test_2_cat.txt"
    "tests/test_3_cat.txt"
    "-n tests/test_3_cat.txt"
    "-b tests/test_3_cat.txt"
    "-s tests/test_3_cat.txt"
    "-t tests/test_3_cat.txt"
    "-e tests/test_3_cat.txt"
    "-n -b tests/test_3_cat.txt"
    "-n -s tests/test_3_cat.txt"
    "-n -t tests/test_3_cat.txt"
    "-n -e tests/test_3_cat.txt"
    "-b -s tests/test_3_cat.txt"
    "-b -t tests/test_3_cat.txt"
    "-b -e tests/test_3_cat.txt"
    "-s -t tests/test_3_cat.txt"
    "-s -e tests/test_3_cat.txt"
    "-t -e tests/test_3_cat.txt"
    "-n -b -s tests/test_3_cat.txt"
    "-n -b -t tests/test_3_cat.txt"
    "-n -b -e tests/test_3_cat.txt"
    "-n -s -t tests/test_3_cat.txt"
    "-n -s -e tests/test_3_cat.txt"
    "-n -t -e tests/test_3_cat.txt"
    "-b -s -t tests/test_3_cat.txt"
    "-b -s -e tests/test_3_cat.txt"
    "-b -t -e tests/test_3_cat.txt"
    "-s -t -e tests/test_3_cat.txt"
    "-n -b -s -t tests/test_3_cat.txt"
    "-n -b -s -e tests/test_3_cat.txt"
    "-n -b -t -e tests/test_3_cat.txt"
    "-n -s -t -e tests/test_3_cat.txt"
    "-b -s -t -e tests/test_3_cat.txt"
    "-n -b -s -t -e tests/test_3_cat.txt"
    "tests/test_4_cat.txt"
    "-n tests/test_4_cat.txt"
    "-b tests/test_4_cat.txt"
    "-s tests/test_4_cat.txt"
    "-t tests/test_4_cat.txt"
    "-e tests/test_4_cat.txt"
    "-n -b tests/test_4_cat.txt"
    "-n -s tests/test_4_cat.txt"
    "-n -t tests/test_4_cat.txt"
    "-n -e tests/test_4_cat.txt"
    "-b -s tests/test_4_cat.txt"
    "-b -t tests/test_4_cat.txt"
    "-b -e tests/test_4_cat.txt"
    "-s -t tests/test_4_cat.txt"
    "-s -e tests/test_4_cat.txt"
    "-t -e tests/test_4_cat.txt"
    "-n -b -s tests/test_4_cat.txt"
    "-n -b -t tests/test_4_cat.txt"
    "-n -b -e tests/test_4_cat.txt"
    "-n -s -t tests/test_4_cat.txt"
    "-n -s -e tests/test_4_cat.txt"
    "-n -t -e tests/test_4_cat.txt"
    "-b -s -t tests/test_4_cat.txt"
    "-b -s -e tests/test_4_cat.txt"
    "-b -t -e tests/test_4_cat.txt"
    "-s -t -e tests/test_4_cat.txt"
    "-n -b -s -t tests/test_4_cat.txt"
    "-n -b -s -e tests/test_4_cat.txt"
    "-n -b -t -e tests/test_4_cat.txt"
    "-n -s -t -e tests/test_4_cat.txt"
    "-b -s -t -e tests/test_4_cat.txt"
    "-n -b -s -t -e tests/test_4_cat.txt"
)

GREEN='\033[32m'
RED='\033[31m'
NC='\033[0m'

echo "-----RUNNING CAT TESTS-----"

i=1
failed=0

run_test() {
    local flags=$1

    echo -e "Running test: ./s21_cat $flags"

    cat $flags > cat_output.txt 2>/dev/null

    gcc -o s21_cat s21_cat.c
    ./s21_cat $flags > s21_cat_output.txt 2>/dev/null

    leaks -atExit -- ./s21_cat $flags > leaks_output.txt
    memory_leak=$(grep "LEAK:" leaks_output.txt)

    diff_result=$(diff -s cat_output.txt s21_cat_output.txt)

    if [ "$diff_result" == "Files cat_output.txt and s21_cat_output.txt are identical" ]; then
        if [ -z "$memory_leak" ]; then
            echo -e " TEST #$i ${GREEN}PASSED${NC}"
        else
            echo -e " TEST #$i ${RED}FAILED (MEMORY LEAK)${NC}"
            echo "$memory_leak"
            ((failed++))
        fi
    else
        echo -e " TEST #$i ${RED}FAILED${NC}"
        echo "$diff_result"
        ((failed++))
    fi

    ((i++))
    rm -f cat_output.txt s21_cat_output.txt leaks_output.txt s21_cat
}

for test_case in "${TESTS[@]}"; do
    run_test "$test_case"
done

echo "-----TESTING COMPLETE-----"
echo -e "Total tests: $i"
echo -e "Failed tests: $failed"
